### ISSUE TITLE
Add Docker support

### ISSUE THREAD

**Issue by JacksonCoder** [SouthEugeneRoboticsTeam/dunk#10]
C++ is one of the more annoying languages to work with when you have to configure your system to have the right libraries, the right header files, etc.

We could benefit greatly if we have a Dockerfile to handle installation.

It would also be cool if we could get someone on the software team with little to no experience in C++ to work on this, because it's a great learning moment and a good introduction to Docker and how C++ libraries link together, but it's not super difficult.

**Comment by andrewda** [comment]
https://github.com/SouthEugeneRoboticsTeam/dunk/blob/master/Dockerfile ??

**Comment by JacksonCoder** [comment]
How did I miss that?
